from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class LLMMessage(BaseModel):
    """Normalized message turn passed to an LLM engine."""
    role: str = Field(..., description="Role: 'system', 'user', or 'assistant'")
    content: str = Field(..., description="Message text content")


class LLMRequest(BaseModel):
    """Normalized completion request dispatched to any LLM provider."""
    messages: List[LLMMessage] = Field(..., description="List of prompt and conversation messages")
    temperature: Optional[float] = Field(default=0.75, ge=0.0, le=2.0)
    top_p: Optional[float] = Field(default=0.9, ge=0.0, le=1.0)
    max_tokens: Optional[int] = Field(default=2048, ge=1)
    stream: bool = Field(default=False)
    extra_options: Dict[str, Any] = Field(default_factory=dict)


class LLMTokenUsage(BaseModel):
    """Token consumption metadata returned by the provider."""
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None
    total_tokens: Optional[int] = None


class LLMResponse(BaseModel):
    """Normalized response payload returned by any LLM provider."""
    content: str = Field(..., description="Assistant reply generated by the model")
    model: str = Field(..., description="Model identifier that produced the reply")
    provider: str = Field(..., description="Provider name (e.g. ollama, gemini)")
    latency_ms: float = Field(..., description="Inference latency in milliseconds")
    usage: Optional[LLMTokenUsage] = Field(default=None, description="Token consumption metrics")
    raw_response: Optional[Dict[str, Any]] = Field(default=None, description="Raw provider payload if available")


class ProviderMetadata(BaseModel):
    """Provider-agnostic operational health metadata."""
    name: str
    current_model: str
    is_cloud: bool
    healthy: bool
    details: Dict[str, Any] = Field(default_factory=dict)


class LLMProvider(ABC):
    """Abstract interface for all JESTER brain implementations.
    
    JESTER Core never knows whether the brain is Ollama, Gemini, OpenAI,
    or another provider. The provider is swappable via configuration.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of the provider (e.g. 'ollama', 'gemini', 'openai', 'mock')."""
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Name of the configured active model (e.g. 'qwen3.6:latest')."""
        pass

    @abstractmethod
    async def chat(self, request: LLMRequest) -> LLMResponse:
        """Executes a completion/chat request against the model engine."""
        pass

    @abstractmethod
    async def health_check(self) -> ProviderMetadata:
        """Checks connectivity and operational status."""
        pass
